openapi: 3.0.1
info:
  title: Education Service REST API
  version: v1
servers:
  - description: 'Local'
    url: 'http://localhost'
tags:
  - description: Education
    name: education
paths:
  /api/education/{userId}:
    get:
      description: This request retrieves all user education matching the userId.
      operationId: getUserEducation
      parameters:
        - in: path
          required: true
          name: userId
          schema:
            type: integer
            default: 0
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEducation'
          description: OK
        '401':
          description: Unauthorized
        '403':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Forbidden
      tags:
        - education
components:
  schemas:
    UserEducation:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        title:
          type: string
          example: English
        level:
          type: string
          example: intermediate
        createdAt:
          type: string
          format: date
          example: 2017-12-06
        updatedAt:
          type: string
          format: date
          example: 2017-12-06
    ErrorInfo:
      type: object
      properties:
        exception:
          type: string
        message:
          type: string
