openapi: 3.0.1
info:
  title: Skills Service REST API
  version: v1
servers:
  - description: 'Local'
    url: 'http://localhost'
tags:
  - description: Skills
    name: skills
paths:
  /api/skills/{userId}:
    get:
      description: This request retrieves all user skills matching the userId.
      operationId: getUserSkills
      parameters:
        - in: path
          required: true
          name: userId
          schema:
            type: integer
            default: 0
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSkills'
          description: OK
        '401':
          description: Unauthorized
        '403':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Forbidden
      tags:
        - skills
components:
  schemas:
    UserSkills:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        tech:
          type: string
          example: java
        seniority:
          type: string
          example: senior
        createdAt:
          type: string
          format: date
          example: 2017-12-06
        updatedAt:
          type: string
          format: date
          example: 2017-12-06
    ErrorInfo:
      type: object
      properties:
        exception:
          type: string
        message:
          type: string
