openapi: 3.0.1
info:
  title: Roles Service REST API
  version: v1
servers:
  - description: 'Local'
    url: 'http://localhost'
tags:
  - description: Roles
    name: roles
paths:
  /api/auth/roles/{userId}:
    get:
      description: This request retrieves all user roles matching the userId.
      operationId: getUserRoles
      parameters:
        - in: path
          required: true
          name: userId
          schema:
            type: integer
            default: 0
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRoles'
          description: OK
        '401':
          description: Unauthorized
        '403':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Forbidden
      tags:
        - users
components:
  schemas:
    UserRoles:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        role:
          type: string
          example: user
        createdAt:
          type: string
          format: date
          example: 2017-12-06
        updatedAt:
          type: string
          format: date
          example: 2017-12-06
    ErrorInfo:
      type: object
      properties:
        exception:
          type: string
        message:
          type: string
